name: kits
main: com.minecraftfunpark.kits
version: 2.4
api-version: 1.14
website: http://www.minecraftfunpark.com
depend: [BountifulAPI]
description: >
             Crea y modifica kits personalizables ingame
commands:
  kit:
    description: Spawn an available kit
  kits:
    description: Display a list of available kits
permissions:
  kits.*:
    description: Gives player permission to all Kits commands
    default: op
    children:
      kits.admin: true
      kits.list: true
      kits.sign: true
      kits.flags.*: true
  kits.admin:
    description: Gives players permission to Kits admin commands
    default: op
  kits.list:
    description: Gives players permission to list available Kits
    default: op
  kits.sign:
    description: Gives players permission to use Kit signs
    default: op
  kits.flags.*:
    description: Gives players permission to Kit flags
    default: op
    children:
      kits.flags.overwrite: true
      kits.flags.announce: true
      kits.flags.clear: true
      kits.flags.delay: true
  kits.flags.overwrite:
    description: Gives players permission to use the Overwrite flag
    default: op
  kits.flags.announce:
    description: Gives players permission to use the Announce flag
    default: op
  kits.flags.clear:
    description: Gives players permission to use the Clear flag
    default: op
  kits.flags.delay:
    description: Gives players permission to use the Delay flag
    default: op
